import Mathlib

/-!
# What goes into each PR

This file is the packaging plan of `PR_SPLIT.md` written as Lean: one namespace per proposed
upstream pull request, containing **exactly** the declarations that PR should contain, in the
final naming and argument order recommended after the last review round
(`PR1_MODULAR_REVIEW.md`, `GOLF.md`). Everything here compiles, so the contents of each PR can be
read off — and checked — from a single file.

Conventions used below.

* `PR1`, `PR2`, `PR3` — the three PRs. Each is self-contained: no namespace uses a declaration
  from another, matching the requirement that each PR be green on its own.
* Inside each namespace, a `caller_*` theorem is a replacement proof for an existing Mathlib
  declaration. Where the statement is unchanged, an `example : @caller_foo = @Foo := rfl`
  immediately afterwards machine-checks that the PR does not silently alter the statement.
* `NotPosted` collects the material that is deliberately *not* shipped, each item with the rule
  from `PR_SPLIT.md §0` that excludes it. Nothing there is a live declaration.

The splitting rule (`PR_SPLIT.md §0`), for reference: the same PR carries the lemma, its
`@[to_dual]` partner, the caller rewrites it enables, and golfs inside hunks already touched;
a different PR carries anything independently justifiable — other file or typeclass API, extra
hypotheses, unrelated golf churn, or a generalisation with no caller yet.
-/

open Set Filter

set_option autoImplicit false

namespace PRPlan

/-! ## PR 1 — diagonal collapse for doubly indexed suprema, and its three callers

**Title:** `feat(Order/CompleteLattice): diagonal collapse for doubly indexed suprema`
**File touched:** `Mathlib/Order/CompleteLattice/Basic.lean` (next to `iSup_mono'`/`iSup₂_mono'`),
plus the three caller files.

Contents, in order: one new theorem (whose dual is generated, hence part of the same declaration),
then the three caller rewrites that justify it. Two scope decisions to state in the PR body:

* the lemma is stated over `CompleteSemilatticeSup`, not `CompleteLattice` — the `iSup_le`/`le_iSup`
  API would force the stronger class for no gain;
* the proof deliberately stays on `sSup_le`/`le_sSup`: the shorter `iSup_le`/`le_iSup` golf a
  reviewer will suggest breaks `@[to_dual]` (the translated term keeps a `SupSet` projection where
  an `InfSet` one is needed).
-/

namespace PR1

/-- **The lemma of PR 1.** A doubly indexed supremum equals the supremum along its diagonal when
the diagonal is cofinal: every entry `f i j` is dominated by some diagonal entry `f k k`.

The infimum version `iInf₂_eq_iInf_diagonal` is generated by `@[to_dual]` and is part of this same
declaration — never a separate PR. -/
@[to_dual iInf₂_eq_iInf_diagonal]
theorem iSup₂_eq_iSup_diagonal {α : Type*} {ι : Sort*} [CompleteSemilatticeSup α]
    (f : ι → ι → α) (h : ∀ i j, ∃ k, f i j ≤ f k k) :
    ⨆ i, ⨆ j, f i j = ⨆ k, f k k := by
  refine le_antisymm (sSup_le ?_) (sSup_le ?_) <;> rintro _ ⟨i, rfl⟩
  · refine sSup_le ?_
    rintro _ ⟨j, rfl⟩
    obtain ⟨k, hk⟩ := h i j
    exact hk.trans (le_sSup ⟨k, rfl⟩)
  · exact (le_sSup (s := range (f i)) ⟨i, rfl⟩).trans (le_sSup ⟨i, rfl⟩)

/-- Caller 1 — `ENat.iSup_add_iSup` in `Mathlib/Data/ENat/Lattice.lean`.

The `cases isEmpty_or_nonempty ι` opening stays: `ENat.iSup_add`/`ENat.add_iSup` need
`[Nonempty ι]`. Its empty branch is where the free golf of `PR_SPLIT.md §1` applies — the existing
`simp only [iSup_of_empty, bot_eq_zero, zero_add]` becomes plain `simp`, inside a hunk this PR
opens anyway. -/
theorem caller_enat_iSup_add_iSup {ι : Sort*} {f g : ι → ℕ∞}
    (h : ∀ i j, ∃ k, f i + g j ≤ f k + g k) : iSup f + iSup g = ⨆ i, f i + g i := by
  cases isEmpty_or_nonempty ι
  · simp
  · simp_rw [ENat.iSup_add, ENat.add_iSup]
    exact iSup₂_eq_iSup_diagonal _ h

example : @caller_enat_iSup_add_iSup = @ENat.iSup_add_iSup := rfl

/-- Caller 2 — `ENNReal.iSup_add_iSup` in `Mathlib/Data/ENNReal/Operations.lean`. Same shape as
caller 1; the duplication between the two is precisely what the new lemma removes. -/
theorem caller_ennreal_iSup_add_iSup {ι : Sort*} {f g : ι → ENNReal}
    (h : ∀ i j, ∃ k, f i + g j ≤ f k + g k) : iSup f + iSup g = ⨆ i, f i + g i := by
  cases isEmpty_or_nonempty ι
  · simp
  · simp_rw [ENNReal.iSup_add, ENNReal.add_iSup]
    exact iSup₂_eq_iSup_diagonal _ h

example : @caller_ennreal_iSup_add_iSup = @ENNReal.iSup_add_iSup := rfl

/-- Caller 3 — `ENNReal.iInf_add_iInf`, same file, discharged by the *generated* dual. This caller
is the argument for letting `@[to_dual]` produce `iInf₂_eq_iInf_diagonal` rather than omitting it:
the dual is not speculative API, it has a duplicate caller of its own. (There is no
`ENat.iInf_add_iInf`, so this third caller is `ℝ≥0∞`-only.) -/
theorem caller_ennreal_iInf_add_iInf {ι : Sort*} {f g : ι → ENNReal}
    (h : ∀ i j, ∃ k, f k + g k ≤ f i + g j) : iInf f + iInf g = ⨅ a, f a + g a := by
  simp_rw [ENNReal.iInf_add, ENNReal.add_iInf]
  exact iInf₂_eq_iInf_diagonal _ h

example : @caller_ennreal_iInf_add_iInf = @ENNReal.iInf_add_iInf := rfl

/-! ### Optional modular form of PR 1

If a reviewer asks for the general statement behind the diagonal case (the review in
`PR1_MODULAR_REVIEW.md` proposes it), PR 1 can instead ship the two theorems below and derive
`iSup₂_eq_iSup_diagonal` from the second. This is a *choice about PR 1*, not extra material:

* it adds one further theorem, `Modular.iSup₂_eq_iSup_of_forall_exists_le`;
* it moves `Modular.iSup_eq_iSup_of_forall_exists_le` out of PR 3 and into PR 1, leaving PR 3 with
  the set-level `IsCofinalFor` pair and the two subsequence callers;
* the callers above are unchanged, and the typeclass stays `CompleteSemilatticeSup`, so all the
  scope notes still hold.

Do not ship both forms. -/

namespace Modular

/-- Mutually cofinal families have the same supremum. (In the modular form of PR 1 this replaces
PR 3's indexed pair.) -/
@[to_dual]
theorem iSup_eq_iSup_of_forall_exists_le {α : Type*} {ι κ : Sort*} [CompleteSemilatticeSup α]
    {f : ι → α} {g : κ → α} (hfg : ∀ i, ∃ j, f i ≤ g j) (hgf : ∀ j, ∃ i, g j ≤ f i) :
    ⨆ i, f i = ⨆ j, g j := by
  refine le_antisymm (sSup_le ?_) (sSup_le ?_) <;> rintro _ ⟨i, rfl⟩
  · obtain ⟨j, hj⟩ := hfg i
    exact hj.trans (le_sSup ⟨j, rfl⟩)
  · obtain ⟨j, hj⟩ := hgf i
    exact hj.trans (le_sSup ⟨j, rfl⟩)

/-- A doubly indexed supremum collapses onto any family cofinal in it. -/
@[to_dual iInf₂_eq_iInf_of_forall_exists_le]
theorem iSup₂_eq_iSup_of_forall_exists_le {α : Type*} {ι κ ν : Sort*} [CompleteSemilatticeSup α]
    (F : ι → κ → α) (G : ν → α) (hle : ∀ i j, ∃ k, F i j ≤ G k)
    (hge : ∀ k, ∃ i j, G k ≤ F i j) :
    ⨆ i, ⨆ j, F i j = ⨆ k, G k := by
  refine le_antisymm (sSup_le ?_) (sSup_le ?_) <;> rintro _ ⟨i, rfl⟩
  · refine sSup_le ?_
    rintro _ ⟨j, rfl⟩
    obtain ⟨k, hk⟩ := hle i j
    exact hk.trans (le_sSup ⟨k, rfl⟩)
  · obtain ⟨a, b, hab⟩ := hge i
    exact hab.trans ((le_sSup (s := range (F a)) ⟨b, rfl⟩).trans (le_sSup ⟨a, rfl⟩))

/-- In the modular form, the shipped diagonal lemma is this one-liner, and its dual is again
generated. -/
@[to_dual iInf₂_eq_iInf_diagonal]
theorem iSup₂_eq_iSup_diagonal {α : Type*} {ι : Sort*} [CompleteSemilatticeSup α]
    (F : ι → ι → α) (h : ∀ i j, ∃ k, F i j ≤ F k k) :
    ⨆ i, ⨆ j, F i j = ⨆ k, F k k :=
  iSup₂_eq_iSup_of_forall_exists_le F _ h fun k => ⟨k, k, le_rfl⟩

end Modular

end PR1

/-! ## PR 2 — the conditionally complete diagonal lemma, and the `Cardinal` caller

**Title:** `feat(Order/ConditionallyCompleteLattice): diagonal collapse for conditionally complete
suprema`
**Files touched:** `Mathlib/Order/ConditionallyCompleteLattice/Indexed.lean` (next to
`ciSup_mono_of_forall_exists`) and `Mathlib/SetTheory/Cardinal/Arithmetic.lean`.

Separate from PR 1 by rules 4 and 5: different file, different API, an extra `BddAbove` hypothesis
that needs its own review argument, and its own caller. Neither PR depends on the other, so the
two can be open simultaneously; fold PR 2 into PR 1 only if a reviewer asks.

Argument order is `(f) (hf) (h)` — boundedness first, matching `ciSup_mono_of_forall_exists`
(`PR_SPLIT.md §5`). The pinned Mathlib of this project predates that neighbouring lemma, so a
private shim stands in for it below; the shim is scaffolding, not part of the PR.
-/

namespace PR2

private theorem ciSup_mono_of_forall_exists {α : Type*} {ι κ : Sort*}
    [ConditionallyCompleteLattice α] [Nonempty ι] {f : ι → α} {g : κ → α}
    (hg : BddAbove (range g)) (h : ∀ i, ∃ k, f i ≤ g k) : ⨆ i, f i ≤ ⨆ k, g k := by
  refine ciSup_le fun i ↦ ?_
  obtain ⟨k, hk⟩ := h i
  exact hk.trans (le_ciSup hg k)

/-- **The lemma of PR 2.** The conditionally complete diagonal collapse: boundedness of the
diagonal plus cofinality of the diagonal bounds the whole square family and collapses the double
supremum.

No `Nonempty ι` hypothesis: for empty `ι` both sides are `sSup ∅`. Dropping it is what makes the
`ConditionallyCompleteLinearOrderBot` variant requested on Zulip redundant (see `NotPosted`), a
finding to report in the PR text rather than in code. -/
theorem ciSup₂_eq_ciSup_diagonal {α : Type*} {ι : Sort*} [ConditionallyCompleteLattice α]
    (f : ι → ι → α) (hf : BddAbove (range fun k ↦ f k k)) (h : ∀ i j, ∃ k, f i j ≤ f k k) :
    ⨆ i, ⨆ j, f i j = ⨆ k, f k k := by
  cases isEmpty_or_nonempty ι
  · rw [iSup_of_empty', iSup_of_empty']
  · -- The central fact: every entry is below the diagonal supremum, `f i j ≤ ⨆ k, f k k`.
    have hle : ∀ i j, f i j ≤ ⨆ k, f k k := fun i j ↦
      let ⟨k, hk⟩ := h i j; hk.trans (le_ciSup hf k)
    have hrow : ∀ i, BddAbove (range (f i)) := fun i ↦ ⟨_, forall_mem_range.2 (hle i)⟩
    have hcol : BddAbove (range fun i ↦ ⨆ j, f i j) :=
      ⟨_, forall_mem_range.2 fun i ↦ ciSup_le (hle i)⟩
    exact le_antisymm (ciSup_le fun i ↦ ciSup_mono_of_forall_exists hf (h i))
      (ciSup_le fun k ↦ le_ciSup_of_le hcol k (le_ciSup (hrow k) k))

/-- The caller of PR 2 — a new `Cardinal.ciSup_add_ciSup_diagonal` strengthening
`Cardinal.ciSup_add_ciSup`. `Cardinal` is a `ConditionallyCompleteLinearOrderBot`, not a complete
lattice, so this caller genuinely needs the conditionally complete lemma; that is why it travels
with PR 2 rather than PR 1. -/
protected theorem Cardinal.ciSup_add_ciSup_diagonal {ι : Type*} [Nonempty ι] (f g : ι → Cardinal)
    (hf : BddAbove (range f)) (hg : BddAbove (range g))
    (h : ∀ i j, ∃ k, f i + g j ≤ f k + g k) :
    (⨆ i, f i) + (⨆ j, g j) = ⨆ k, f k + g k := by
  obtain ⟨bf, hbf⟩ := id hf
  obtain ⟨bg, hbg⟩ := id hg
  rw [Cardinal.ciSup_add_ciSup f hf g hg]
  exact ciSup₂_eq_ciSup_diagonal (fun i j ↦ f i + g j)
    ⟨bf + bg, by rintro _ ⟨k, rfl⟩; exact add_le_add (hbf ⟨k, rfl⟩) (hbg ⟨k, rfl⟩)⟩ h

/-! ### Optional companion for PR 2

`IsCofinalFor.bddAbove` (proposed as part (a) of the modular draft) has no caller in PR 1, but it
does discharge the *inner* boundedness side condition of the lemma above: each row is cofinal in
the diagonal, so it inherits the diagonal's bound. If part (a) is shipped at all, PR 2 is where it
is load-bearing. The *outer* condition `BddAbove (range fun i ↦ ⨆ j, f i j)` is not an instance of
it — a row supremum need not lie below any single diagonal entry — so the proof above still builds
that bound by hand. -/

/-- Cofinal subsets of a bounded-above set are bounded above. -/
@[to_dual IsCoinitialFor.bddBelow]
theorem IsCofinalFor.bddAbove {α : Type*} [Preorder α] {s t : Set α} (h : IsCofinalFor s t)
    (ht : BddAbove t) : BddAbove s :=
  ht.imp fun _ hc => upperBounds_mono_of_isCofinalFor h hc

example {α : Type*} {ι : Sort*} [ConditionallyCompleteLattice α] (f : ι → ι → α)
    (hf : BddAbove (range fun k ↦ f k k)) (h : ∀ i j, ∃ k, f i j ≤ f k k) (i : ι) :
    BddAbove (range (f i)) :=
  IsCofinalFor.bddAbove
    (by rintro _ ⟨j, rfl⟩; obtain ⟨k, hk⟩ := h i j; exact ⟨f k k, ⟨k, rfl⟩, hk⟩) hf

end PR2

/-! ## PR 3 — suprema of mutually cofinal families agree

**Title:** `feat(Order): suprema of mutually cofinal families agree`
**Files touched:** the home of `sSup_le_sSup_of_isCofinalFor` (`Mathlib/Order/CompleteLattice/…`)
and `Mathlib/Topology/Order/MonotoneConvergence.lean`.

Separate by rule 4: it is a statement about the existing `IsCofinalFor` predicate, self-justifying
as the equality companion of the existing one-sided lemmas `sSup_le_sSup_of_isCofinalFor` /
`sInf_le_sInf_of_isCoinitialFor`. Open it after PR 1 or PR 2 has been merged.

Contents: the set-level pair, the indexed pair derived from it on ranges, and the two subsequence
caller rewrites. Their two `iInf` counterparts delegate to these and improve transitively —
mention that in the PR body, do not rewrite them.

If PR 1 is submitted in its modular form, the indexed pair below has already landed there; PR 3
then consists of the set-level pair plus the two callers only.
-/

namespace PR3

/-- Mutually cofinal sets have the same supremum. -/
theorem sSup_eq_sSup_of_isCofinalFor {α : Type*} [CompleteSemilatticeSup α] {s t : Set α}
    (hst : IsCofinalFor s t) (hts : IsCofinalFor t s) : sSup s = sSup t :=
  le_antisymm (sSup_le_sSup_of_isCofinalFor hst) (sSup_le_sSup_of_isCofinalFor hts)

/-- Mutually coinitial sets have the same infimum. Written out by hand rather than generated,
because the `≤`-halves `sSup_le_sSup_of_isCofinalFor` / `sInf_le_sInf_of_isCoinitialFor` are
themselves not `to_dual`-linked upstream. -/
theorem sInf_eq_sInf_of_isCoinitialFor {α : Type*} [CompleteSemilatticeInf α] {s t : Set α}
    (hst : IsCoinitialFor s t) (hts : IsCoinitialFor t s) : sInf s = sInf t :=
  le_antisymm (sInf_le_sInf_of_isCoinitialFor hts) (sInf_le_sInf_of_isCoinitialFor hst)

/-- The indexed corollary, obtained by applying the set-level lemma to the two ranges. -/
theorem iSup_eq_iSup_of_forall_exists_le {α : Type*} {ι κ : Sort*} [CompleteSemilatticeSup α]
    {f : ι → α} {g : κ → α} (hfg : ∀ i, ∃ k, f i ≤ g k) (hgf : ∀ k, ∃ i, g k ≤ f i) :
    ⨆ i, f i = ⨆ k, g k := by
  rw [iSup, iSup]
  refine sSup_eq_sSup_of_isCofinalFor ?_ ?_
  · rintro _ ⟨i, rfl⟩
    obtain ⟨k, hik⟩ := hfg i
    exact ⟨g k, ⟨k, rfl⟩, hik⟩
  · rintro _ ⟨k, rfl⟩
    obtain ⟨i, hki⟩ := hgf k
    exact ⟨f i, ⟨i, rfl⟩, hki⟩

/-- The indexed dual. -/
theorem iInf_eq_iInf_of_forall_exists_le {α : Type*} {ι κ : Sort*} [CompleteSemilatticeInf α]
    {f : ι → α} {g : κ → α} (hfg : ∀ i, ∃ k, g k ≤ f i) (hgf : ∀ k, ∃ i, f i ≤ g k) :
    ⨅ i, f i = ⨅ k, g k := by
  rw [iInf, iInf]
  refine sInf_eq_sInf_of_isCoinitialFor ?_ ?_
  · rintro _ ⟨i, rfl⟩
    obtain ⟨k, hki⟩ := hfg i
    exact ⟨g k, ⟨k, rfl⟩, hki⟩
  · rintro _ ⟨k, rfl⟩
    obtain ⟨i, hik⟩ := hgf k
    exact ⟨f i, ⟨i, rfl⟩, hik⟩

/-- Caller 1 — replacement proof for `iSup_eq_iSup_subseq_of_monotone`. -/
theorem caller_iSup_eq_iSup_subseq_of_monotone {ι₁ ι₂ α : Type*} [Preorder ι₂] [CompleteLattice α]
    {l : Filter ι₁} [l.NeBot] {f : ι₂ → α} {φ : ι₁ → ι₂} (hf : Monotone f)
    (hφ : Tendsto φ l atTop) : ⨆ i, f i = ⨆ i, f (φ i) :=
  iSup_eq_iSup_of_forall_exists_le
    (fun i ↦ Exists.imp (fun _ hij ↦ hf hij) (hφ.eventually <| eventually_ge_atTop i).exists)
    (fun i ↦ ⟨φ i, le_rfl⟩)

example : @caller_iSup_eq_iSup_subseq_of_monotone = @iSup_eq_iSup_subseq_of_monotone := rfl

/-- Caller 2 — replacement proof for `iSup_eq_iSup_subseq_of_antitone`. -/
theorem caller_iSup_eq_iSup_subseq_of_antitone {ι₁ ι₂ α : Type*} [Preorder ι₂] [CompleteLattice α]
    {l : Filter ι₁} [l.NeBot] {f : ι₂ → α} {φ : ι₁ → ι₂} (hf : Antitone f)
    (hφ : Tendsto φ l atBot) : ⨆ i, f i = ⨆ i, f (φ i) :=
  iSup_eq_iSup_of_forall_exists_le
    (fun i ↦ Exists.imp (fun _ hji ↦ hf hji) (hφ.eventually <| eventually_le_atBot i).exists)
    (fun i ↦ ⟨φ i, le_rfl⟩)

example : @caller_iSup_eq_iSup_subseq_of_antitone = @iSup_eq_iSup_subseq_of_antitone := rfl

end PR3

/-! ## Not posted (yet)

Each item below is checked elsewhere in this project but stays out of all three PRs. The code is
commented out on purpose: this section is a list of decisions, not a list of declarations.
-/

namespace NotPosted

/-! ### 1. The `ConditionallyCompleteLinearOrderBot` variant — duplicate API

Once `Nonempty ι` is dropped from `PR2.ciSup₂_eq_ciSup_diagonal`, this is *literally the same
statement*, since such an order is a conditionally complete lattice. Report the collapse in the PR
description; do not ship a second declaration. Recorded in `RequestProject/NextPR.lean`.

```lean
theorem ciSup₂_eq_ciSup_diagonal' {α : Type*} {ι : Sort*} [ConditionallyCompleteLinearOrderBot α]
    (f : ι → ι → α) (hf : BddAbove (range fun k ↦ f k k)) (h : ∀ i j, ∃ k, f i j ≤ f k k) :
    ⨆ i, ⨆ j, f i j = ⨆ k, f k k :=
  PR2.ciSup₂_eq_ciSup_diagonal f hf h
```

### 2. Re-deriving the diagonal lemma through mutual cofinality — generality loss

It works, via `iSup_prod'`, but it forces the index from `Sort*` down to `Type*`. So PR 1 keeps its
direct proof and stays independent of PR 3.

```lean
example {α : Type*} {ι : Type*} [CompleteLattice α] (f : ι → ι → α)
    (h : ∀ i j, ∃ k, f i j ≤ f k k) : ⨆ i, ⨆ j, f i j = ⨆ k, f k k := by
  rw [iSup_prod' (f := fun i j => f i j)]
  exact PR3.iSup_eq_iSup_of_forall_exists_le (fun p => h p.1 p.2) (fun k => ⟨(k, k), le_rfl⟩)
```

### 3. Multiplicative analogues — no caller (rule 7)

`ennreal_iSup_mul_iSup` and `enat_iSup_mul_iSup` do compile from the same diagonal lemma, and need
no `Nonempty ι` (checked in `RequestProject/PR1Modular.lean`), but nothing upstream uses them.

### 4. The cofinal-subset chain — overlaps PR 3

`sSup_eq_sSup_of_subset_of_isCofinalFor`, the indexed subfamily/reindexing lemmas and the
`iSup_ne_bot_subtype` refactor (`RequestProject/SubsetTransitiveCallers.lean`) are credible as a
later PR, but overlap PR 3's content. Wait until PR 3 lands and a reviewer asks.

### 5. The `Monotone.iSup_comp_eq` refactor — churn, not simplification (rule 6)

The existing proof is already one line.

### 6. Style variants and new abstractions

The ~20 term-mode/`calc`/`iSup_mono'` variants in `RequestProject/DiagonalVariations.lean` are
exploration only; a "cofinal subfamily" typeclass or a general
binary-operation-commutes-with-suprema abstraction is new framework, against the stated preference
for small discoverable lemmas.
-/

end NotPosted

/-! ## Posting order

1. **PR 1** — smallest, three existing duplicate callers, no new hypotheses.
2. **PR 2** — in parallel; link it from PR 1 and state there that the `…Bot` variant collapses into
   the general lemma.
3. **PR 3** — after PR 1 or PR 2 merges; then reconsider `NotPosted` §4 in light of the review.
-/

end PRPlan
