/-
Machine-checked support for the proposed Mathlib contribution described in
`CONTRIBUTION.md` (patch: `contribution/reflect-to_additive.patch`).

Context: the exercise sheet asks (Exercise 1.14 a) for the Gauss summation formula
`1 + 2 + ... + n = n(n+1)/2`, which Mathlib proves as `Finset.sum_range_id_mul_two`
in `Mathlib/Algebra/BigOperators/Intervals.lean`, using the reflection lemma
`Finset.sum_range_reflect` from the same file.  Exercise 1.19 (binomial identities)
touches `Nat.sum_range_choose_halfway`, which uses `Finset.sum_Ico_reflect`.

In current Mathlib both additive lemmas are written out by hand as
  `theorem sum_Ico_reflect ... := @prod_Ico_reflect (Multiplicative δ) _ f k m n h`
  `theorem sum_range_reflect ... := @prod_range_reflect (Multiplicative δ) _ f n`
instead of being generated by `@[to_additive]` from the multiplicative versions.

This file checks the only thing that has to be true for the proposed deletion to be
safe: putting `@[to_additive]` on the multiplicative lemmas produces additive lemmas
whose statements are *literally* the ones currently in Mathlib, so the two hand-written
declarations can be deleted without any change to the public API.
-/
import Mathlib

namespace KalkulusContribution

open Finset

/-- Copy of `Finset.prod_Ico_reflect` (same statement, same proof), but tagged
`@[to_additive]`, which generates `KalkulusContribution.sum_Ico_reflect'`. -/
@[to_additive]
theorem prod_Ico_reflect' {M : Type*} [CommMonoid M] (f : ℕ → M) (k : ℕ) {m n : ℕ}
    (h : m ≤ n + 1) :
    (∏ j ∈ Ico k m, f (n - j)) = ∏ j ∈ Ico (n + 1 - m) (n + 1 - k), f j := by
  have hmn : ∀ i < m, i ≤ n := by
    intro i hi
    exact (add_le_add_iff_right 1).1 (le_trans (Nat.lt_iff_add_one_le.1 hi) h)
  rcases lt_or_ge k m with hkm | hkm
  · rw [← Nat.Ico_image_const_sub_eq_Ico (hmn _ hkm)]
    refine (prod_image ?_).symm
    simp only [mem_Ico, Set.InjOn, mem_coe]
    rintro i ⟨_, im⟩ j ⟨_, jm⟩ Hij
    rw [← tsub_tsub_cancel_of_le (hmn _ im), Hij, tsub_tsub_cancel_of_le (hmn _ jm)]
  · have hnk : n + 1 - k ≤ n + 1 - m := by
      rw [tsub_le_tsub_iff_left h]
      exact hkm
    simp only [hkm, Ico_eq_empty_of_le, prod_empty, Ico_eq_empty_of_le hnk]

/-- Copy of `Finset.prod_range_reflect` (same statement, same proof), but tagged
`@[to_additive]`, which generates `KalkulusContribution.sum_range_reflect'`. -/
@[to_additive]
theorem prod_range_reflect' {M : Type*} [CommMonoid M] (f : ℕ → M) (n : ℕ) :
    (∏ j ∈ range n, f (n - 1 - j)) = ∏ j ∈ range n, f j := by
  cases n
  · simp
  · simp only [← Nat.Ico_zero_eq_range, Nat.succ_sub_succ_eq_sub, tsub_zero]
    rw [prod_Ico_reflect' _ _ le_rfl]
    simp

/-- The `@[to_additive]`-generated lemma has exactly the type of the hand-written
`Finset.sum_Ico_reflect`; the equality would not even typecheck otherwise. -/
theorem sum_Ico_reflect_statements_agree :
    @sum_Ico_reflect' = @Finset.sum_Ico_reflect := rfl

/-- The `@[to_additive]`-generated lemma has exactly the type of the hand-written
`Finset.sum_range_reflect`; the equality would not even typecheck otherwise. -/
theorem sum_range_reflect_statements_agree :
    @sum_range_reflect' = @Finset.sum_range_reflect := rfl

end KalkulusContribution
