/-
Checks that the moved lemma is where the patch puts it, that `@[to_additive]`
generates the additive twin, and that both statements are the old ones.
Run with:  lake env lean check_import_bump.lean
-/
module

public import Mathlib.GroupTheory.GroupAction.Basic
public import Mathlib.GroupTheory.OrderOfElement

/-- The multiplicative lemma is available from the stabilizer file alone. -/
example {G : Type*} [Group G] {x y : G} {α : Type*} [MulAction G α]
    (hx : x ∈ Subgroup.zpowers y) {a : α} (hs : y • a = a) : x • a = a :=
  smul_eq_self_of_mem_zpowers hx hs

/-- The additive twin is generated by `@[to_additive]`, with its old statement. -/
example {G : Type*} [AddGroup G] {x y : G} {α : Type*} [AddAction G α]
    (hx : x ∈ AddSubgroup.zmultiples y) {a : α} (hs : y +ᵥ a = a) : x +ᵥ a = a :=
  vadd_eq_self_of_mem_zmultiples hx hs

#check @smul_eq_self_of_mem_zpowers
#check @vadd_eq_self_of_mem_zmultiples
